import {
  Accordion,
  AudioPlayer,
  CountAnimation,
  DropDown,
  InfiniteAnimation,
  Modal,
} from "@/components";
import { faq } from "@/mock/data";
import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const [isOpen, setIsOpen] = useState(false);

  const handleClose = () => {
    setIsOpen(false)
  };
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <InfiniteAnimation className="mt-50" />
      <AudioPlayer
        className="mt-50"
        tracks={[
          {
            src: "1.mp3",
          },
        ]}
      />
      <DropDown className="mt-50" />
      <CountAnimation className="mt-50" number={"1212"} duration={"4"} />
      <Accordion className="mt-50" value={faq} />

      <button className="mt-50" onClick={() => setIsOpen(true)}>Show modal</button>

      <Modal handleClose={handleClose} isOpen={isOpen}>
        <h2>Hello</h2>
      </Modal>
    </div>
  );
}
